name: guide-stable-diffusion
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel=6
  - jupyter_core=5.7
  - matplotlib=3.8
  - palettable=3.3
  - numpy=1.23
  - tqdm=4.65
  - einops=0.7
  - pytorch-cuda=12.4
  - pytorch=2.4
  - torchvision=0.19
  - torchaudio=2.4
  - lightning=2.2
  - openai=1.37
  - botorch=0.11
  - wandb=0.16
  - diffusers=0.31.0
  - accelerate=1.0.1
  - scipy=1.12
  - python-dotenv=1.0.1
  - transformers=4.50
  - open-clip-torch=2.24.0
  - cma=3.3
  - scikit-learn=1.4.2
  - gpytorch::gpytorch=1.11
  - ipywidgets=8.1
  - seaborn=0.13
  - pip:
    - jsonargparse[signatures]==4.27.7
    - python-pptx==1.0.2
    - google-generativeai==0.7.*
    - --pre oneflow -f https://github.com/siliconflow/oneflow_releases/releases/expanded_assets/community_cu122
    - --pre onediff