# pytorch cli config
seed_everything: 0

trainer:
  log_every_n_steps: 1
  max_epochs: 50
  logger:
    class_path: WandbLogger
    init_args:
      project: finetune-stable-diffusion
      name: finetune-with-model
  callbacks:
  - class_path: WandbModelCheckpoint
    init_args:
      monitor: "train/score_mean"
      mode: max
      save_top_k: -1
      save_last: True
      every_n_epochs: 10
      filename: '{epoch:03d}'
data:
  class_path: datamodule.DummyDataModule
  init_args: {}
model:
  class_path: models.finetune_with_model.FinetuneDiffusionWithModel
  init_args:
    sd_model: sdxl-lightning
    training_batch_size: 32
    lr: 100.0
    reg: 0.00
    # generate_prompt: "A dolphin riding a cool motorcycle on the beach."
    # reward_target_prompt: "A dolphin riding a cool motorcycle on the beach, the image appears to be natural and realistic."
    # generate_prompt: "A dog and a bear sharing an ice cream."
    # reward_target_prompt: "A dog and a bear sharing an ice cream."
    # generate_prompt: "A white puppy with golden wings."
    # reward_target_prompt: "A white puppy that has golden wings spread out nicely on its body back."
    generate_prompt: "A dog riding on a bear."
    reward_target_prompt: "A dog riding on a bear."
    # generate_prompt: "A transparent glass vase filled with a mixture of water and sand, with a single floating feather inside."
    # reward_target_prompt: "A transparent glass vase filled with a mixture of water and sand, with a single floating feather inside."
    # reward_func: "llava"
    # reward_query_prompt: "Describe this photo concisely."
    reward_func: "gemini-question"
    reward_query_prompt: "Describe this image concisely in one scentence."

# base_lr=50

# sd2: alpha=1
# sdxl: alpha=2
# gpt/gemini: beta=1
# llava: beta=2

# lr = base_lr * alpha * beta
