# pytorch cli config
seed_everything: 0

trainer:
  check_val_every_n_epoch: 5
  log_every_n_steps: 1
  max_epochs: 50
  logger:
    class_path: WandbLogger
    init_args:
      project: finetune-stable-diffusion
      name: finetune-with-model
  callbacks:
  - class_path: ModelCheckpoint
    init_args:
      every_n_epochs: 10
      save_top_k: -1
      filename: '{epoch:03d}'
      save_on_train_epoch_end: True
data:
  class_path: datamodule.DummyDataModule
  init_args: {}
model:
  class_path: models.finetune_with_model.FinetuneDiffusionWithModel
  init_args:
    compile: True
    guidance_model: "gp"
    sd_model: sdxl-lightning
    training_batch_size: 32
    validation_batch_size: 16
    validation_load_epsilon: results/epsilons/all.pt
    alpha: 80 # guidance step
    reg_mode: "projection"
    reg: 1e-3
    generate_prompt: "A yellow reindeer and a blue elephant."
    reward_target_prompt: "A yellow reindeer and a blue elephant."
    reward_func: "gemini-question"
    reward_query_prompt: null
    max_reward_value: 5.0