# pytorch cli config
seed_everything: 0

trainer:
  check_val_every_n_epoch: 10
  log_every_n_steps: 1
  max_epochs: 200
  logger:
    class_path: WandbLogger
    init_args:
      project: guide-stable-diffusion
      name: guide-with-optimization
  callbacks:
  - class_path: ModelCheckpoint
    init_args:
      every_n_epochs: 10
      save_top_k: -1
      filename: '{epoch:03d}'
      save_on_train_epoch_end: True
data:
  class_path: datamodule.DummyDataModule
  init_args: {}
model:
  class_path: models.guide_with_optimization.GuideDiffusionWithOptimization
  init_args:
    compile: True
    sd_model: sdxl-ddim
    lr_mu: 256 # sqrt(d)
    lr_sigma: 1
    projection: True
    training_batch_size: 32
    validation_batch_size: 16

    reward_func: "gemini-question"
    generate_prompt: "A robotic cat and a robotic dog playing with a football on the moon. The cat wearing a hat, and dog wearing a scarf."
    reward_target_prompt: "A robotic cat and a robotic dog playing with a football on the moon. The cat wearing a hat, and dog wearing a scarf."
    reward_query_prompt: "Does the image accurately aligned with the prompt '{target_prompt}', why? Answer score=0 (no) or score=1 (yes).\nAnswer in the format: Reason=reason, Score=score."
    max_reward_value: 1.0

    use_value_model: True